django/first_django_project/first_django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('myApp.urls', namespace='app'))
]

django/first_django_project/myApp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),  # 用正则匹配
    url(r'^class/$', views.classes),
    url(r'^student/$', views.students, name='xioshengwaer'),
    url(r'^class/(\d+)$', views.class_students),
    url(r'^student/(\d+)$', views.student_info),
    url(r'^studentsearch/$', views.student_search),
    url(r'^classsearch/$', views.class_search),
    url(r'^attr/$', views.attr),
    url(r'^get1/$', views.get1),
    url(r'^get2/$', views.get2),
    url(r'^register/$', views.register),
    url(r'^showregister/$', views.showregister),
    url(r'^redirect1/$', views.redirect1),
    url(r'^redirect2/$', views.redirect2),
    url(r'^main/$', views.main),
    url(r'^showmain/$', views.showmain),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.qt),
    url(r'^test/$', views.test, name='shazidongxi'),
    url(r'^firstpage/$', views.firstpage),
    url(r'^upfile/$', views.upfile),
    url(r'^savefile/$', views.savefile, name='savefile')
]

django/first_django_project/myApp/models.py
from django.db import models


# Create your models here.
class Class(models.Model):
    cname = models.CharField(max_length=20)
    cdate = models.DateField()
    cgirl_num = models.IntegerField()
    cboy_num = models.IntegerField()
    is_delete = models.BooleanField()

    def __str__(self):
        return "班级名：{cname}\n创建时间：{cdate}".format(cname=self.cname, cdate=self.cdate)
    class Meta:
        ordering = ['cname']
        db_table = 'class'

class Students(models.Model):
    sname = models.CharField(max_length=20)  # 字符型，最大长度为20字节
    sgender = models.BooleanField(default=True)  # boolean类型 设置默认为True
    sage = models.IntegerField()  # 整型
    scomment = models.CharField(max_length=20)
    is_delete = models.BooleanField()
    # 关联外键
    sclass = models.ForeignKey("Class")

    class Meta:
        db_table = "students"
        ordering = ['id']

django/first_django_project/myApp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import Class, Students
from django.db.models import *


def index(request):
    return HttpResponse('jyw666')


def classes(request):
    # 去模板里取数据
    # class_list = Class.objects.all()
    # 将数据传递给模板，模板再渲染页面，将渲染号的页面，返回给浏览器
    class_list = Class.objects.filter(cgirl_num__lt=F('cboy_num'))
    return render(request, 'myApp/class.html', {"classes": class_list})


def students(request):
    student_list = Students.objects.all()
    return render(request, 'myApp/student.html', {"students": student_list})


def class_students(request, num):
    # 获得对应的班级对象
    class1 = Class.objects.get(pk=num)
    # 获得学生集合
    student_list = class1.students_set.all()
    return render(request, 'myApp/student.html', {"students": student_list})


def student_info(request, num):
    student = Students.objects.get(pk=num)
    return render(request, 'myApp/student_info.html', {"student": student})


def student_search(request):
    # student_list = Students.objects.filter(sname__contains='a')
    # student_list = Students.objects.filter(sname__startswith='j', sname__endswith='i')
    # student_list = Students.objects.filter(sname__in=['jiangyuwei', 'baoqianyue'])
    # student_list = Students.objects.filter(sage__gt=100)
    # print(Students.objects.aggregate(Max('sage')))
    student_list = Students.objects.filter(Q(sage__gt=10) | Q(sclass_id__gt=2))
    student_list1 = Students.objects.filter(sage__gt=10, sclass_id__gt=2)
    print(student_list)
    print(student_list1)
    return render(request, 'myApp/student.html', {'students': student_list})


def class_search(request):
    class_list = Class.objects.filter(cdate__month=2)
    return render(request, 'myApp/class.html', {'classes': class_list})


def attr(request):
    print('path', request.path)
    print('method', request.method)
    print('encoding', request.encoding)
    print('GET', request.GET)
    print('POST', request.POST)
    print('FILES', request.FILES)
    print('COOKIES', request.COOKIES)
    print('session', request.session)

    return HttpResponse('asd')


def get1(request):
    a = request.GET.get('a')
    b = request.GET.get('b')
    c = request.GET.get('c')
    return HttpResponse(a + ' ' + b + ' ' + c)


def get2(request):
    a = request.GET.getlist('a')
    c = request.GET.get('c')
    print(a)
    return HttpResponse(' '.join(a) + ' ' + c)


def register(request):
    """
    获取表单并显示
    """
    name = request.POST.get('name')
    gender = request.POST.get('gender')
    age = request.POST.get('age')
    if 1 == int(gender):
        gender = '男'
    else:
        gender = '女'
    hobby = request.POST.getlist('hobby')
    response = HttpResponse('姓名:' + name + '\n' + '性别:' + gender + '\n' + '年龄:' + age + '\n' + '爱好:' + ','.join(hobby))
    print(response.status_code)
    print(response.content)
    print(response.charset)
    return response


def showregister(request):
    """
    显示注册界面
    """
    return render(request, 'myApp/register.html')


def redirect1(request):
    return redirect('/redirect2')


def redirect2(request):
    return HttpResponse('重定向')


# session+重定向
def main(request):
    # 取出session
    username = request.session.get('username')
    if username:
        pass
    else:
        username = '未登录，请先登录'
    return render(request, 'myApp/main.html', {'username': username})


def login(request):
    return render(request, 'myApp/login.html')


def showmain(request):
    username = request.POST.get('username')
    print(username)
    # 储存session
    request.session['username'] = username
    # request.session.set_expiry(10)# 10秒后过期
    # request.session.set_expiry()# 10秒后过期
    return redirect('/main')


from django.contrib.auth import logout


def qt(request):
    # 清楚session
    logout(request)
    # request.session.clear()
    # request.session.flush()
    return redirect('/main')


def test(request):
    return render(request, 'myApp/test.html', {'test_list': [11, 'asd']})


def firstpage(request):
    return render(request, 'myApp/firstpage.html')


def upfile(request):
    return render(request, 'myApp/upfile.html')


TEST_PATH = '.'
import os


def savefile(request):
    if request.method == "POST":
        f = request.FILES.get('file')
        path = os.path.join(TEST_PATH, f.name)
        with open(path, 'wb') as fp:
            for per in f.chunks():
                fp.write(per)
        return HttpResponse('上传成功')
    else:
        return HttpResponse('fuck wrong')

django/first_django_project/templates/myApp/ajax_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <button id="btn">显示</button>
{#    <script type="text/javascript" src=" "></script>#}
</body>
</html>

django/first_django_project/templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #header{
            width: 100%;
            height: 100px;
            background-color: aqua;
        }
        #floor{
            width: 100%;
            height: 100px;
            background-color: rebeccapurple;
        }
    </style>
</head>
<body>
<div id="header">header</div>
<div id="main">
    {% block main %}
    {% endblock main %}
</div>
<div id="floor">floor</div>

</body>
</html>

django/first_django_project/templates/myApp/class.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>班级信息</title>
</head>
<body>
<h1>班级信息列表</h1>
<u1>
    <!--[jiangyuwei, wangtianrui, baoqianyue]-->
    {%for class in classes%}
    <li>
        <a href="{{class.id}}">{{class.cname}}</a>
    </li>
    {%endfor%}
</u1>
</body>
</html>

django/first_django_project/templates/myApp/firstpage.html
{% extends 'myApp/base.html' %}

{% block main %}
    <h1>
        NICE
    </h1>
{% endblock main %}

django/first_django_project/templates/myApp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
    <form action="/showmain/" method="post">
        <input type="text" name="username" value="">
        <input type="submit" value="注册">
    </form>
</body>
</html>

django/first_django_project/templates/myApp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人主页</title>
</head>
<body>
    <h1>
        {{ username }}
    </h1>
    <a href="/login/">登陆</a>
    <a href="/logout/">退出登陆</a>
</body>
</html>

django/first_django_project/templates/myApp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="/register/" method="post">
        姓名:<input type="text" name="name" value=""/>
        <hr/>
        性别:<input type="radio" name="gender" value="1"/>男
            <input type="radio" name="gender" value="0"/>女
        <hr/>
        年龄:<input type="text" name="age" value=""/>
        <hr/>
        爱好:<input type="checkbox" name="hobby" value="football"/>足球
            <input type="checkbox" name="hobby" value="basketball"/>篮球
            <input type="checkbox" name="hobby" value="pingpang"/>乒乓球
        <hr/>
        <input type="submit" value="注册"/>

    </form>
</body>
</html>

django/first_django_project/templates/myApp/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
</head>
<body>
    <h1>学生信息</h1>
    <ul>
        {%for student in students%}
        <li>
            <a href="{{student.id}}">{{student.sname}}</a> --
            <!--先获取班级对象，再获取班级名属性-->
            {{student.sclass.cname}}
        </li>
        {%endfor%}
    </ul>
</body>
</html>

django/first_django_project/templates/myApp/student_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生信息</title>
</head>
<body>
    <h1>学生信息</h1>
    <ul>
        姓名：{{student.sname}}
        简介：{{student.scomment}}
    </ul>
</body>
</html>

django/first_django_project/templates/myApp/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试</title>
</head>
<body>
    {% ifequal 'a' 'a' %}
        <h1>asd</h1>
    {% endifequal %}

    <h1>{{ test_list|join:'@' }}</h1>
    <h1>{{ test1|default:'没有' }}</h1>

    <a href="{% url 'app:xioshengwaer' %}">链接</a>
</body>
</html>

django/first_django_project/templates/myApp/upfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传文件</title>
</head>
<body>
    <form method="post" action="/savefile/" enctype="multipart/form-data">
        <input type="file" name="file"/>
        <input type="submit" value="上传"/>
    </form>
</body>
</html>